name: Check
on:
  - push
  - pull_request
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.7.0'
      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Typecheck
        run: yarn tsc
      - name: Lint
        run: yarn lint
      - name: Prettier
        run: yarn prettier . --check
